/** PDF-based test workflow. In-memory only; never writes a sanitary record. */
function createHygieneWorkflow(kind, initial={}) {
const today=new Date();
const TODAY=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');
const field=(key,label,type='text',extra={})=>({key,label,type,required:true,...extra});
const pick=(key,label,options,extra={})=>field(key,label,'radio',{options,...extra});
const yes=(key,label,extra={})=>field(key,label,'checkbox',extra);
const num=(key,label,extra={})=>field(key,label,'number',{step:'any',...extra});
const txt=(key,label,extra={})=>field(key,label,'textarea',extra);
const step=(id,title,doText,source,fields,extra={})=>({id,title,doText,source,fields,...extra});
const entered=v=>v!==undefined&&v!==null&&String(v).trim()!=='';
const value=(d,k)=>entered(d[k])?Number(String(d[k]).replace(',','.')):null;
const bad=(d,keys)=>keys.some(k=>['Refusé','Présence','Non conforme','Non contrôlé','Non évalué','Impossible','À signaler','Non réalisé','Absent'].includes(d[k]));
const lotFields=[field('product','Dénomination du produit','text'),field('supplier','Fournisseur'),field('lot','Numéro de lot'),field('received','Date de réception','date')];lotFields[0].type='text';
const dateFields=[field('day','Journée de la fiche','date'),field('observed','Date et heure réelles du contrôle','datetime-local'),txt('late','Motif de la saisie différée',{show:d=>entered(d.day)&&d.day<TODAY,help:'Le jour contrôlé et le jour de saisie restent distincts.'})];
const issueFields=[txt('finding','Constat / anomalie'),txt('action','Action effectuée ou mesure conservatoire'),field('actionAt','Date et heure de cette action','datetime-local'),field('owner','Responsable à informer / chargé du suivi'),pick('followStatus','Suite du contrôle',['À recontrôler','Vérification réalisée']),txt('followResult','Résultat de la vérification',{show:d=>d.followStatus==='Vérification réalisée'}),field('followAt','Date et heure de la vérification','datetime-local',{show:d=>d.followStatus==='Vérification réalisée'}),field('due','Échéance de suivi','datetime-local',{show:d=>d.followStatus==='À recontrôler'} )];
const commonInstrument=[field('probeId','Sonde utilisée'),pick('probeValid','Vérification mensuelle de la sonde',['À jour','Indisponible / expirée']),yes('probeClean','J’ai nettoyé et désinfecté la sonde.',{show:d=>d.probeValid==='À jour'}),txt('probeReason','Motif / sonde de remplacement à prévoir',{show:d=>d.probeValid==='Indisponible / expirée'})];
const canMeasure=d=>d.probeValid==='À jour';
const sourceNames={fresh:'PDF p. 3–4 · cahier p. 13–12',receipt:'PDF p. 1–2 · cahier p. 03–02',temp:'PDF p. 5–6 · cahier p. 19–18',tank:'PDF p. 9–10 · cahier p. 33–32',clean:'PDF p. 7–8 · cahier p. 27–26',cook:'PDF p. 11–12 · cahier p. 35–34',probe:'PDF p. 2, 6 et 12 · cahier p. 02, 18, 34'};
function hasIssue(kind,d){
 if(kind==='fresh')return bad(d,['aspect','parasite','sizeVerdict'])||d.gridReady==='Non'||d.sizeReady==='Non';
 if(kind==='receipt')return ['Réserve','Refus'].includes(d.decision)||d.probeValid==='Indisponible / expirée'||bad(d,['coreVerdict','packing','label','aspect','parasite','sizeVerdict','ice','film','truck','weightVerdict'])||d.tempReady==='Non'||d.uvcVerdict==='Non évalué';
 if(kind==='temp')return d.equipmentState==='Hors service'||d.probeValid==='Indisponible / expirée'||bad(d,['tempVerdict'])||d.tempReady==='Non';
 if(kind==='tank')return d.tankState==='Hors service'||d.tankMeasured==='Impossible'||(value(d,'salinity')!==null&&(value(d,'salinity')<1020||value(d,'salinity')>1025))||d.tankConcern==='À signaler';
 if(kind==='clean')return d.planReady==='Non'||d.cleanOutcome==='Non réalisé / partiel';
 if(kind==='cook')return (d.coolIn&&d.cookOut&&d.coolIn>d.cookOut)||cookingBlocked(d)||d.probeValid==='Indisponible / expirée'||d.scheduleReady==='Non'||d.cookVerdict==='Non conforme'||d.coolMeasured==='Impossible'||coolingState(d)==='outside';
 if(kind==='probe')return d.bathMeasured==='Impossible'||(value(d,'bath')!==null&&Math.abs(value(d,'bath'))>=.9);
 return false;
}
function cookingBlocked(d){return d.family==='Autre produit'||(d.origin==='Étal'&&d.customer==='Non');}
function coolingState(d){if(!entered(d.cookOut)||!entered(d.coolOut)||value(d,'coolTemp')===null)return 'unknown';const mins=(new Date(d.coolOut)-new Date(d.cookOut))/60000;if(!Number.isFinite(mins)||mins<0)return 'invalid';if(mins>=120||value(d,'coolTemp')>10)return 'outside';return value(d,'coolTemp')<=4?'target':'tolerance';}
function unfinished(kind,d){return (['fresh'].includes(kind)&&(d.gridReady==='Non'||bad(d,['aspect','parasite'])&&['Non évalué','Non contrôlé'].some(x=>[d.aspect,d.parasite].includes(x))||d.sizeReady==='Non'))||(['receipt','temp','cook'].includes(kind)&&(d.probeValid==='Indisponible / expirée'||d.tempReady==='Non'))||(kind==='receipt'&&d.uvcVerdict==='Non évalué')||(kind==='temp'&&['Hors service','Non utilisé'].includes(d.equipmentState))||(kind==='tank'&&(d.tankState==='Hors service'||d.tankMeasured==='Impossible'))||(kind==='clean'&&(d.planReady==='Non'||d.cleanOutcome==='Non réalisé / partiel'))||(kind==='cook'&&(cookingBlocked(d)||d.scheduleReady==='Non'||d.coolMeasured==='Impossible'))||(kind==='probe'&&d.bathMeasured==='Impossible');}
const flows={
fresh:[
 step('context','Identifier la journée et le lot','Sélectionnez la journée réellement contrôlée et le produit que vous avez devant vous.',sourceNames.fresh,[...dateFields,...lotFields,field('location','Lieu du contrôle','text')]),
 step('freshness','Observer la fraîcheur','Examinez le produit en vous référant à la grille fraîcheur du magasin.',sourceNames.fresh,[pick('gridReady','Grille fraîcheur disponible ?',['Oui','Non']),field('grid','Référence / version de la grille','text',{show:d=>d.gridReady==='Oui'}),pick('aspect','Aspect général constaté',['Accepté','Refusé','Non évalué']),txt('aspectNote','Observation sur le produit',{required:false}),txt('missingGrid','Grille indisponible : motif et personne sollicitée',{show:d=>d.gridReady==='Non'})],{note:'Le PDF renvoie à une grille externe. Aucun score de fraîcheur n’est inventé.',branch:'Aspect refusé ou non évalué → constat et action avant le visa.'}),
 step('parasites','Rechercher les parasites','Effectuez le contrôle visuel d’Anisakis dans les filets concernés.',sourceNames.fresh,[pick('parasite','Résultat du contrôle visuel',['Absence','Présence','Non contrôlé','Non applicable']),txt('parasiteReason','Précisez le constat ou le motif',{show:d=>['Présence','Non contrôlé','Non applicable'].includes(d.parasite)})],{branch:'Présence → écarter la marchandise et tracer le contact fournisseur, comme dans l’exemple du cahier.'}),
 step('size','Contrôler la taille / le calibre','Utilisez une règle plastique nettoyée et désinfectée. Comparez au tableau de référence applicable au produit.',sourceNames.fresh,[pick('sizeApplies','Contrôle de taille applicable ?',['Oui','Non']),txt('sizeNA','Motif de non-applicabilité',{show:d=>d.sizeApplies==='Non'}),yes('rulerClean','La règle est nettoyée et désinfectée.',{show:d=>d.sizeApplies==='Oui'}),pick('sizeReady','Référence de taille disponible ?',['Oui','Non'],{show:d=>d.sizeApplies==='Oui'}),field('sizeRef','Référence du tableau de tailles','text',{show:d=>d.sizeApplies==='Oui'&&d.sizeReady==='Oui'}),num('size','Taille mesurée (cm)',{min:0,show:d=>d.sizeApplies==='Oui'}),num('sizeMin','Taille minimale de référence (cm)',{min:0,show:d=>d.sizeApplies==='Oui'&&d.sizeReady==='Oui'}),pick('sizeVerdict','Résultat taille / calibre',['Accepté','Refusé','Non évalué'],{show:d=>d.sizeApplies==='Oui'} )],{branch:'Taille refusée → observation et action corrective ; référence absente → contrôle non évalué.'})
],
receipt:[
 step('context','Identifier la réception','Vérifiez les informations proposées par l’étiquette et rattachez le contrôle à la bonne livraison.',sourceNames.receipt,[...dateFields,...lotFields,field('dlc','DLC, si indiquée','date',{required:false}),field('delivery','Camion / référence de livraison'),pick('supply','Approvisionnement',['Centrale','Direct']),pick('fullTruck','Livraison d’un camion entier ?',['Oui','Non']),pick('night','Livraison de nuit en SAS ?',['Oui','Non']),field('arrivalAt','Date et heure de livraison','datetime-local',{show:d=>d.night==='Oui'})]),
 step('sample','Choisir les colis à contrôler','Centrale : un colis par camion, pris au milieu de palette. Direct : tous les colis ; pour un camion entier, contrôler les produits les plus sensibles.',sourceNames.receipt,[num('packages','Nombre de colis dans la livraison',{min:1,step:1}),num('checkedPackages','Nombre de colis contrôlés',{min:1,step:1}),field('samplePlace','Colis choisis / emplacement dans la palette'),pick('truck','Propreté de la caisse du camion',['Accepté','Refusé','Non contrôlé']),num('weight','Poids contrôlé (kg)',{min:0}),pick('weightVerdict','Résultat du contrôle poids',['Accepté','Refusé','Non contrôlé'])],{branch:'Livraison de nuit → contrôle à la prise en charge du matin, avec heure réelle conservée.'}),
 step('instrument','Préparer la sonde','Utilisez une sonde vérifiée, nettoyée et désinfectée.',sourceNames.receipt,commonInstrument,{branch:'Sonde indisponible → déclarer la mesure impossible ; aucun relevé fictif.'}),
 step('uvc','Mesurer entre deux UVC','Relevez la température entre deux unités de vente, puis comparez au protocole applicable.',sourceNames.receipt,[pick('tempReady','Protocole applicable disponible ?',['Oui','Non']),field('tempRef','Référence du protocole','text',{show:d=>d.tempReady==='Oui'}),num('uvc','Température entre deux UVC (°C)'),pick('uvcVerdict','Résultat selon le protocole',['Accepté','Non conforme','Non évalué'])],{when:canMeasure,branch:'Non conforme → trois mesures à cœur. Absence de protocole → résultat non évalué.'}),
 step('core','Contrôler trois températures à cœur','Mesurez trois températures produits. La moyenne est calculée à partir de ces trois relevés distincts.',sourceNames.receipt,[num('core1','Température produit 1 à cœur (°C)'),num('core2','Température produit 2 à cœur (°C)'),num('core3','Température produit 3 à cœur (°C)'),pick('coreVerdict','Moyenne selon le protocole applicable',['Accepté','Non conforme'])],{when:d=>canMeasure(d)&&d.uvcVerdict==='Non conforme',branch:'Moyenne non conforme → REFUS, conformément au cahier.'}),
 step('goods','Vérifier les denrées','Vérifiez emballage, étiquetage, aspect général, parasites, taille et glaçage. Ne cochez que les contrôles réellement effectués.',sourceNames.receipt,[...['packing','label','aspect','ice'].map((k,i)=>pick(k,['Emballage','Conformité de l’étiquetage','Aspect général / fraîcheur','Présence de glace'][i],['Accepté','Refusé','Non contrôlé','Non applicable'])),pick('parasite','Contrôle visuel parasite',['Absence','Présence','Non contrôlé','Non applicable']),num('size','Taille mesurée (cm)',{min:0,required:false}),pick('sizeVerdict','Taille réglementaire / calibre',['Accepté','Refusé','Non contrôlé','Non applicable']),pick('film','Film plastique pour filets / darnes',['Accepté','Refusé','Non contrôlé','Non applicable']),txt('goodsNotes','Observations / motifs des contrôles non effectués',{required:false})],{when:d=>d.coreVerdict!=='Non conforme',branch:'Un contrôle non fait doit être expliqué. Refus thermique déjà établi → passage direct à l’action et à la décision.'}),
 step('decision','Décider de la réception','Choisissez la décision et complétez les observations qui accompagneront votre visa.',sourceNames.receipt,[pick('decision','Décision',['Réception','Réserve','Refus']),txt('decisionNote','Observation / motif de la décision')])
],
temp:[
 step('context','Choisir l’équipement et le créneau','Réalisez les relevés matin et après-midi, ou le relevé hebdomadaire pour un système avec enregistrement automatique et alarme.',sourceNames.temp,[...dateFields,field('equipment','Équipement / localisation'),pick('equipmentState','État de l’équipement',['En service','Non utilisé','Hors service']),txt('equipmentReason','Motif / précision',{show:d=>['Non utilisé','Hors service'].includes(d.equipmentState)}),pick('automatic','Enregistrement automatique ET alarme ?',['Oui','Non','Configuration à vérifier']),pick('slot','Créneau',['Matin','Après-midi','Hebdomadaire'])]),
 step('instrument','Préparer la sonde','Vérifiez la sonde et nettoyez-la avant la mesure.',sourceNames.temp,commonInstrument,{when:d=>d.equipmentState==='En service'}),
 step('measure','Effectuer le relevé','Mesurez au bon endroit : chambre froide, laboratoire, produit de l’étal ou zone du libre-service.',sourceNames.temp,[pick('method','Méthode / objet de mesure',['Air','Entre 2 UVC','À cœur']),field('measuredProduct','Nom du produit et lot contrôlé','text',{show:d=>['Entre 2 UVC','À cœur'].includes(d.method)}),field('zone','Zone du linéaire / point précis'),num('temperature','Température lue (°C)'),pick('tempReady','Règle de comparaison disponible ?',['Oui','Non']),field('tempRef','Référence du protocole','text',{show:d=>d.tempReady==='Oui'}),pick('tempVerdict','Résultat du relevé',['Accepté','Non conforme','Non évalué'])],{when:d=>d.equipmentState==='En service'&&canMeasure(d),note:'Saisir la valeur lue. La correction doit être liée à la sonde et à une convention validée ; son signe n’est pas deviné.',branch:'Non conforme ou non évalué → constat, action et suivi. Les zones du LS sont contrôlées de manière tournante sur la semaine.'})
],
tank:[
 step('context','Identifier le vivier','Contrôlez chaque vivier séparément. Le relevé de salinité est enregistré une fois par semaine dans le cahier.',sourceNames.tank,[...dateFields,field('tank','Vivier / identifiant'),pick('tankState','État du vivier',['En service avec animaux','Vide mais en service','Hors service']),txt('tankReason','Motif / situation du vivier',{show:d=>d.tankState==='Hors service'})],{branch:'Vivier vide en service → les mesures restent à faire. Hors service → motif et suivi, sans valeur inventée.'}),
 step('water','Mesurer les paramètres','Plongez le densimètre dans le vivier et lisez la valeur indiquée. Relevez également la température.',sourceNames.tank,[pick('tankMeasured','Mesures réalisables ?',['Oui','Impossible']),field('densityTool','Densimètre utilisé','text',{show:d=>d.tankMeasured==='Oui'}),num('salinity','Mesure de la salinité — lecture densimètre',{show:d=>d.tankMeasured==='Oui',help:'Notation du cahier : cible 1022, plage 1020 à 1025. Aucune conversion en g/L.'}),num('waterTemp','Température du vivier (°C)',{show:d=>d.tankMeasured==='Oui',help:'Le PDF indique environ 13 °C, sans plage numérique de tolérance.'}),pick('tankConcern','Autre anomalie observée ?',['Aucune observée','À signaler'],{show:d=>d.tankMeasured==='Oui'}),txt('waterReason','Motif / anomalie constatée',{show:d=>d.tankMeasured==='Impossible'||d.tankConcern==='À signaler'})],{when:d=>d.tankState!=='Hors service',branch:'Lecture <1020 ou >1025, autre anomalie ou mesure impossible → action corrective.'}),
 step('tank-action','Tracer l’action et le recontrôle','Enregistrez l’action réellement effectuée selon la procédure du site. Conservez le premier relevé.',sourceNames.tank,[txt('finding','Constat'),txt('action','Action effectuée selon la procédure du site'),field('actionAt','Date et heure de l’action','datetime-local'),field('owner','Responsable du suivi'),pick('tankRecheck','Recontrôle effectué ?',['Oui','Pas encore']),field('followAt','Date et heure du recontrôle','datetime-local',{show:d=>d.tankRecheck==='Oui'}),num('salinity2','Nouvelle lecture densimètre',{show:d=>d.tankRecheck==='Oui'}),num('waterTemp2','Nouvelle température (°C)',{show:d=>d.tankRecheck==='Oui'}),field('due','Échéance du recontrôle','datetime-local',{show:d=>d.tankRecheck==='Pas encore'})],{when:d=>hasIssue('tank',d),branch:'Le visa enregistre le constat et le suivi. Il ne clôture pas automatiquement l’incident.'})
],
clean:[
 step('context','Choisir la tâche de nettoyage','Repérez la zone et l’élément à nettoyer dans le planning de nettoyage et désinfection.',sourceNames.clean,[...dateFields,pick('cleanZone','Zone',['Chambre froide','Laboratoire','Plonge','Zone de vente','Meubles LS']),field('cleanObject','Élément / équipement à nettoyer'),pick('period','Périodicité du planning',['Poste / jour','Semaine','Trimestre','Semestre','Année']),pick('planReady','Protocole de la tâche disponible ?',['Oui','Non'])]),
 step('plan','Vérifier le protocole','Consultez le produit, la dose, la température de l’eau et le temps d’action indiqués au planning.',sourceNames.clean,[field('cleanPlan','Référence du protocole'),field('cleanProduct','Produit de nettoyage / désinfection'),field('concentration','Dose ou concentration, avec unité'),num('waterSet','Température d’eau prescrite (°C)'),num('contactMinutes','Temps d’action prescrit (minutes)',{min:0}),field('cleanMethod','Méthode prévue au planning')],{when:d=>d.planReady==='Oui',note:'Ces valeurs doivent venir du planning réel. Le PDF ne fournit pas de dose universelle.'}),
 step('perform','Réaliser le nettoyage','Utilisez la bonne dose et l’eau à la bonne température, pulvérisez/frottez, laissez agir puis rincez.',sourceNames.clean,[pick('cleanOutcome','Opération réalisée intégralement ?',['Oui','Non réalisé / partiel']),yes('doseOk','La dose de produit prescrite a été respectée.',{show:d=>d.cleanOutcome==='Oui'}),yes('waterOk','L’eau est à la température prescrite.',{show:d=>d.cleanOutcome==='Oui'}),yes('rubOk','La méthode de nettoyage a été exécutée.',{show:d=>d.cleanOutcome==='Oui'}),yes('contactOk','Le temps d’action a été respecté.',{show:d=>d.cleanOutcome==='Oui'}),yes('rinseOk','Le rinçage a été effectué.',{show:d=>d.cleanOutcome==='Oui'}),field('cleanEnd','Date et heure de fin','datetime-local',{show:d=>d.cleanOutcome==='Oui'}),txt('cleanReason','Ce qui reste à faire / motif',{show:d=>d.cleanOutcome==='Non réalisé / partiel'})],{when:d=>d.planReady==='Oui',branch:'Partiel ou non réalisé → motif et action ; le visa ne coche pas la tâche comme terminée.'})
],
cook:[
 step('context','Identifier le produit à cuire','Vérifiez que le produit et sa provenance correspondent aux conditions du cahier.',sourceNames.cook,[...dateFields,field('product','Dénomination du produit'),field('lot','Numéro de lot'),num('quantity','Quantité',{min:0}),pick('quantityUnit','Unité',['kg','pièces']),field('dlc','DLC attribuée selon le protocole','date'),pick('family','Famille de produit',['Coquillages','Crustacés','Autre produit']),pick('origin','Provenance',['État de livraison','Étal']),pick('customer','Cuisson à la demande du client ?',['Oui','Non'],{show:d=>d.origin==='Étal'})],{branch:'Le PDF autorise coquillages/crustacés dans leur état de livraison ; l’origine étal nécessite la demande du client.'}),
 step('instrument','Préparer la sonde','Utilisez une sonde vérifiée, nettoyée et désinfectée pour les températures à cœur.',sourceNames.cook,commonInstrument,{when:d=>!cookingBlocked(d)}),
 step('schedule','Choisir le barème et le matériel','Programmez le matériel selon le barème de cuisson applicable au produit.',sourceNames.cook,[field('oven','Four / matériel utilisé'),pick('scheduleReady','Barème de cuisson disponible ?',['Oui','Non']),field('schedule','Référence / version du barème','text',{show:d=>d.scheduleReady==='Oui'}),yes('programmed','Le matériel est programmé selon ce barème.',{show:d=>d.scheduleReady==='Oui'})],{when:d=>!cookingBlocked(d)&&canMeasure(d),note:'Le barème est référencé dans le PDF, mais n’y est pas fourni.'}),
 step('cook-out','Contrôler la sortie de cuisson','Mesurez la température à cœur en sortie de cuisson, puis commencez immédiatement le refroidissement en cellule.',sourceNames.cook,[field('cookStart','Date et heure de début de cuisson','datetime-local'),field('cookOut','Date et heure de sortie cuisson','datetime-local'),num('cookTemp','Température à cœur en sortie cuisson (°C)'),pick('cookVerdict','Résultat selon le barème',['Accepté','Non conforme']),field('cell','Cellule de refroidissement'),field('coolIn','Date et heure d’entrée en cellule','datetime-local'),yes('coolProgrammed','La cellule est programmée selon le protocole.')],{when:d=>!cookingBlocked(d)&&canMeasure(d)&&d.scheduleReady==='Oui'}),
 step('cool-out','Contrôler la sortie de cellule','Mesurez à cœur en sortie de cellule et enregistrez l’heure réelle.',sourceNames.cook,[pick('coolMeasured','Mesure de sortie disponible ?',['Oui','Impossible']),field('coolOut','Date et heure de sortie cellule','datetime-local',{show:d=>d.coolMeasured==='Oui'}),num('coolTemp','Température à cœur en sortie cellule (°C)',{show:d=>d.coolMeasured==='Oui'}),txt('coolReason','Motif de la mesure manquante',{show:d=>d.coolMeasured==='Impossible'})],{when:d=>!cookingBlocked(d)&&canMeasure(d)&&d.scheduleReady==='Oui',note:'Cahier : cible +4 °C en moins de 2 h ; tolérance +10 °C en moins de 2 h. Si la température finale dépasse +10 °C, tracer l’élimination prescrite par la fiche.',branch:'Dépassement du temps, de la température ou mesure absente → action et visa du constat.'})
],
probe:[
 step('context','Identifier la sonde','Effectuez cette vérification une fois par mois, avec un bain d’eau glacée.',sourceNames.probe,[...dateFields,field('probeId','Identifiant de la sonde')]),
 step('bath','Lire la sonde au bain d’eau glacée','Plongez la sonde dans le bain et consignez la valeur lue.',sourceNames.probe,[pick('bathMeasured','Vérification réalisable ?',['Oui','Impossible']),yes('bathReady','J’ai utilisé un bain d’eau glacée.',{show:d=>d.bathMeasured==='Oui'}),num('bath','Température lue (°C)',{show:d=>d.bathMeasured==='Oui'}),txt('bathReason','Motif de l’impossibilité',{show:d=>d.bathMeasured==='Impossible'})],{branch:'Lecture ≤ −0,9 °C ou ≥ +0,9 °C → remplacement de la sonde.'}),
 step('replace','Déclarer le remplacement','Le cahier demande le remplacement. Enregistrez la mise à l’écart et la suite donnée.',sourceNames.probe,[yes('probeWithdrawn','Cette sonde est écartée des nouveaux relevés.'),txt('action','Action / remplacement engagé'),field('owner','Responsable du remplacement'),field('replacement','Nouvelle sonde, si déjà disponible','text',{required:false})],{when:d=>value(d,'bath')!==null&&Math.abs(value(d,'bath'))>=.9})
]
};
let index=0; const answers={day:TODAY,...initial};
function data(){return answers;}
function issueStep(){return step('issue','Documenter l’écart','Renseignez le constat, l’action effectivement menée et la suite à donner.',sourceNames[kind],issueFields,{branch:'Un suivi en attente reste ouvert après le visa de l’employé.'});}
function visibleSteps(){let list=flows[kind].filter(s=>!s.when||s.when(data()));if(kind!=='tank'&&hasIssue(kind,data())&&!(kind==='probe'&&value(data(),'bath')!==null&&Math.abs(value(data(),'bath'))>=.9))list.push(issueStep());list.push(step('visa','Relire et viser','Relisez vos saisies puis attestez uniquement ce que vous avez réellement observé ou exécuté.',sourceNames[kind],[txt('finalNote','Observation complémentaire',{required:false}),yes('attest','J’atteste l’exactitude de ces observations et des actions déclarées.') ]));return list;}
function visibleFields(s){return s.fields.filter(f=>!f.show||f.show(data()));}

function updateAnswer(key,v){
 const d=data();if(d[key]===v)return;
 const current=visibleSteps()[index];
 const all=[...flows[kind],...(kind==='tank'?[]:[issueStep()]),step('visa','','','',[field('finalNote',''),yes('attest','')])];
 const at=all.findIndex(s=>s.id===current.id);
 const protectedKeys=new Set(current.fields.map(f=>f.key));
 for(const s of all.slice(at+1))for(const f of s.fields)if(!protectedKeys.has(f.key))delete d[f.key];
 d[key]=v;
 // Clear hidden answers, including values in branches that were previously visited.
 for(let pass=0;pass<3;pass++)for(const s of all)for(const f of s.fields){
  if((s.when&&!s.when(d))||(f.show&&!f.show(d)))delete d[f.key];
 }
}

function validate(s){const d=data(),errors=[];for(const f of visibleFields(s)){const v=d[f.key];if(f.required&&(f.type==='checkbox'?v!==true:!entered(v)))errors.push('À renseigner : '+f.label+'.');if(f.type==='number'&&entered(v)&&(!Number.isFinite(value(d,f.key))||(f.min!==undefined&&value(d,f.key)<f.min)||(f.step===1&&!Number.isInteger(value(d,f.key)))))errors.push('Valeur invalide : '+f.label+'.');}
 if(s.id==='context'){if(d.day>TODAY)errors.push('Une journée future peut être planifiée, pas visée comme déjà réalisée.');if(d.observed&&d.observed.slice(0,10)!==d.day)errors.push('La journée doit correspondre au jour réel du contrôle.');}
 if(kind==='fresh'&&s.id==='freshness'&&d.gridReady==='Non'&&d.aspect!=='Non évalué')errors.push('Sans grille, choisissez « Non évalué » et documentez son absence.');
 if(kind==='fresh'&&s.id==='size'&&d.sizeApplies==='Oui'){if(d.sizeReady==='Non'&&d.sizeVerdict!=='Non évalué')errors.push('Sans référence de taille, le résultat est « Non évalué ».');if(d.sizeReady==='Oui'&&value(d,'size')!==null&&value(d,'sizeMin')!==null&&value(d,'size')<value(d,'sizeMin')&&d.sizeVerdict==='Accepté')errors.push('La taille est inférieure à la référence : elle ne peut être acceptée.');}
 if(kind==='receipt'&&s.id==='sample'){if(value(d,'checkedPackages')>value(d,'packages'))errors.push('Le nombre contrôlé dépasse le nombre de colis reçus.');if(d.supply==='Direct'&&d.fullTruck==='Non'&&value(d,'checkedPackages')!==value(d,'packages'))errors.push('Approvisionnement direct : le PDF demande le contrôle de tous les colis.');}
 if(['receipt','temp'].includes(kind)&&['uvc','measure'].includes(s.id)&&d.tempReady==='Non'&&(kind==='receipt'?d.uvcVerdict:d.tempVerdict)!=='Non évalué')errors.push('Sans protocole applicable, sélectionnez « Non évalué ».');
 if(kind==='receipt'&&s.id==='decision'){if(d.coreVerdict==='Non conforme'&&d.decision!=='Refus')errors.push('La moyenne non conforme impose le refus dans le cahier.');if(hasIssue(kind,d)&&d.decision==='Réception')errors.push('Un écart ou contrôle manquant subsiste : choisissez une décision qui le conserve, sans réception simple.');}
 if(kind==='receipt'&&s.id==='goods'&&(bad(d,['packing','label','aspect','parasite','sizeVerdict','ice','film'])||['packing','label','aspect','parasite','sizeVerdict','ice','film'].some(k=>d[k]==='Non applicable'))&&!entered(d.goodsNotes))errors.push('Décrivez les écarts et les contrôles non réalisés.');
 if(kind==='temp'&&s.id==='context'&&d.slot==='Hebdomadaire'&&d.automatic!=='Oui')errors.push('Le relevé hebdomadaire requiert enregistrement automatique ET alarme selon le PDF.');
 if(kind==='cook'&&s.id==='cook-out'){if(entered(d.cookStart)&&entered(d.cookOut)&&d.cookOut<d.cookStart)errors.push('La sortie cuisson doit suivre le début de cuisson.');if(entered(d.coolIn)&&entered(d.cookOut)&&d.coolIn<d.cookOut)errors.push('L’entrée en cellule ne peut précéder la sortie cuisson.');}
 if(kind==='cook'&&s.id==='cool-out'&&d.coolMeasured==='Oui'&&(d.coolOut<d.coolIn||coolingState(d)==='invalid'))errors.push('La sortie cellule doit suivre l’entrée en cellule et la sortie cuisson.');
 if(['issue','tank-action'].includes(s.id)){if(d.actionAt&&d.observed&&d.actionAt<d.observed)errors.push('L’action doit suivre le constat initial.');if(d.followAt&&d.actionAt&&d.followAt<d.actionAt)errors.push('Le recontrôle doit suivre l’action.');}
 for(const f of visibleFields(s)){
  const raw=d[f.key];
  if(entered(raw)&&['date','datetime-local'].includes(f.type)){
   const stamp=new Date(f.type==='date'?raw+'T12:00':raw);
   const valid=Number.isFinite(stamp.getTime())&&String(raw).slice(0,10)===[stamp.getFullYear(),String(stamp.getMonth()+1).padStart(2,'0'),String(stamp.getDate()).padStart(2,'0')].join('-');
   if(!valid)errors.push('Date invalide : '+f.label+'.');
   if(valid&&!['dlc','due'].includes(f.key)&&stamp>new Date()&&f.type==='datetime-local')errors.push('Une observation ne peut pas être datée dans le futur : '+f.label+'.');
  }
 }
 if(s.id==='context'&&d.received&&d.received>d.day)errors.push('La réception ne peut pas suivre la journée contrôlée.');
 if(s.id==='context'&&d.arrivalAt&&d.observed&&d.arrivalAt>d.observed)errors.push('Le contrôle doit suivre la livraison.');
 if(['issue','tank-action'].includes(s.id)&&d.due&&d.actionAt&&d.due<d.actionAt)errors.push('L’échéance doit suivre l’action.');
 return [...new Set(errors)];}

function notes(stepId){const d=data(),s=visibleSteps().find(s=>s.id===stepId);let out=[];
 if(kind==='receipt'&&s?.id==='core'&&['core1','core2','core3'].every(k=>value(d,k)!==null))out.push('Moyenne des trois températures : '+((value(d,'core1')+value(d,'core2')+value(d,'core3'))/3).toFixed(2).replace('.',',')+' °C. Le verdict dépend du protocole applicable.');
 if(kind==='receipt'&&d.coreVerdict==='Non conforme'&&['decision','issue','visa'].includes(s?.id))out.push('La moyenne a été déclarée non conforme : la décision doit être « Refus ».');
 if(kind==='tank'&&['water','tank-action','visa'].includes(s?.id)&&value(d,'salinity')!==null)out.push(value(d,'salinity')<1020||value(d,'salinity')>1025?'Lecture initiale hors de la plage 1020–1025 : action et suivi nécessaires.':'Lecture initiale dans la plage 1020–1025 du cahier. La température reste une observation distincte.');
 if(kind==='tank'&&s?.id==='tank-action'&&value(d,'salinity2')!==null)out.push(value(d,'salinity2')<1020||value(d,'salinity2')>1025?'Le recontrôle reste hors plage : le suivi reste ouvert.':'Recontrôle de salinité dans la plage ; la première mesure reste conservée.');
 if(kind==='probe'&&value(d,'bath')!==null&&['bath','replace','visa'].includes(s?.id))out.push(Math.abs(value(d,'bath'))>=.9?'Seuil de remplacement atteint selon le PDF (≤ −0,9 ou ≥ +0,9 °C).':'Lecture située entre les seuils de remplacement du PDF.');
 if(kind==='cook'&&cookingBlocked(d))out.push('Ce produit ou cette provenance ne remplit pas les conditions de cuisson décrites dans le PDF. Enregistrer un constat, sans valider une cuisson.');
 if(kind==='cook'&&d.coolIn&&d.cookOut&&d.coolIn>d.cookOut)out.push('L’entrée en cellule est postérieure à la sortie cuisson : documenter le délai, le cahier demande un refroidissement immédiat.');
 if(kind==='cook'&&['cool-out','issue','visa'].includes(s?.id)&&coolingState(d)!=='unknown'){const minutes=(new Date(d.coolOut)-new Date(d.cookOut))/60000;out.push(`Durée depuis sortie cuisson : ${Number.isFinite(minutes)?minutes:'—'} min. `+({target:'Cible du cahier atteinte.',tolerance:'Au-dessus de la cible +4 °C, dans la tolérance +10 °C du cahier avant 2 h.',outside:'Hors cible / tolérance ou délai de moins de 2 h non respecté : action à tracer.',invalid:'Heures incohérentes : corriger les dates.'}[coolingState(d)]));}
 if(s?.id==='visa'&&unfinished(kind,d))out.push('Ce visa porte sur un constat incomplet ou une impossibilité. Le contrôle ne sera pas présenté comme terminé et conforme.');
 return out;
}

return {data, steps:visibleSteps, fields:visibleFields, validate, notes,
 update(key,value,stepId){index=visibleSteps().findIndex(s=>s.id===stepId);if(index<0)throw new Error('Unknown step');updateAnswer(key,value);},
 hasIssue:()=>Boolean(hasIssue(kind,data())), unfinished:()=>Boolean(unfinished(kind,data())),
 validateAll:()=>[...new Set(visibleSteps().flatMap(validate))]};

}
export {createHygieneWorkflow};
