"""Export the exact implemented API inventory used for release and pentest scope."""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import yaml

from labelscan.app.http_app import create_app

_ROOT = Path(__file__).resolve().parents[2]
_TARGET = _ROOT / "docs" / "backend" / "openapi.v1.yaml"
_PUBLIC_PATHS = {
    "/v1/auth/login",
    "/v1/o/{organization_slug}/auth/login",
    "/v1/mobile/auth/login",
    "/v1/mobile/auth/refresh",
    "/v1/mobile/auth/logout",
    "/v1/auth/refresh",
    "/v1/auth/logout",
    "/v1/health/live",
    "/v1/health/ready",
    "/v1/version",
}
_METHODS = {"get", "post", "put", "patch", "delete"}


def rendered_schema() -> str:
    os.environ.setdefault("LABELSCAN_ENV", "development")
    schema = create_app().openapi()
    schema["info"]["description"] = (
        "Generated inventory of the currently implemented LabelScan API. "
        "Production disables the interactive OpenAPI and Swagger endpoints; "
        "this reviewed artifact defines pentest scope."
    )
    schema["servers"] = [{"url": "/", "description": "same-origin deployment"}]
    components = schema.setdefault("components", {})
    components.setdefault("schemas", {})["Problem"] = {
        "type": "object",
        "description": "Sanitized RFC 9457-style error envelope.",
        "required": [
            "type",
            "title",
            "status",
            "detail",
            "error_code",
            "timestamp",
            "retriable",
        ],
        "properties": {
            "type": {"type": "string", "format": "uri"},
            "title": {"type": "string"},
            "status": {"type": "integer"},
            "detail": {"type": "string"},
            "error_code": {"type": "string"},
            "correlation_id": {"anyOf": [{"type": "string"}, {"type": "null"}]},
            "trace_id": {"anyOf": [{"type": "string"}, {"type": "null"}]},
            "timestamp": {"type": "string", "format": "date-time"},
            "retriable": {"type": "boolean"},
            "errors": {"type": "array", "items": {"type": "object"}},
        },
    }
    components.setdefault("securitySchemes", {})["bearerAuth"] = {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": (
            "15-minute JWT with jti, sid, issuer, audience, tenant, role, and scopes"
        ),
    }
    for path, operations in schema["paths"].items():
        for method, operation in operations.items():
            if method not in _METHODS:
                continue
            operation["security"] = (
                [] if path in _PUBLIC_PATHS else [{"bearerAuth": []}]
            )
            responses = operation.setdefault("responses", {})
            if responses.pop("422", None) is not None:
                responses.setdefault(
                    "400",
                    {
                        "description": "Request validation failed",
                        "content": {
                            "application/problem+json": {
                                "schema": {"$ref": "#/components/schemas/Problem"}
                            }
                        },
                    },
                )
    body = yaml.safe_dump(schema, sort_keys=False, allow_unicode=True, width=100)
    return (
        "# GENERATED by server/scripts/export_openapi.py — do not edit by hand.\n"
        "# This file inventories implemented endpoints for release review and pentest scope.\n"
        + body
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = rendered_schema()
    if args.check:
        if not _TARGET.exists() or _TARGET.read_text(encoding="utf-8") != rendered:
            print(f"OpenAPI inventory is stale: run {Path(__file__).name}")
            return 1
        print("OpenAPI inventory is current")
        return 0
    _TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {_TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
